# Generated by Django 5.1 on 2024-08-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="railwaycomplaint",
            name="user",
        ),
    ]
