# Generated by Django 5.1 on 2024-08-27 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_department_railwaycomplaint_department_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10 digits only.", regex="^\\d{10}"
                    )
                ],
            ),
        ),
    ]
