# Generated by Django 5.1 on 2024-08-27 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0006_alter_employee_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format +919xxxxxxxxx and 12 digits after the '+' sign.",
                        regex="^\\+\\d{12}$",
                    )
                ],
            ),
        ),
    ]
